CONFIG_SYS_MMCSD_FS_BOOT_PARTITION=y
CONFIG_BOOTM_NETBSD=y
CONFIG_BOOTM_VXWORKS=y
CONFIG_POWER_TPS65217=y
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_SYS_LOAD_ADDR=0x82000000
CONFIG_SYS_HELP_CMD_WIDTH=10
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=1024
CONFIG_SKIP_LOWLEVEL_INIT=y
CONFIG_SYS_SPL_MALLOC_SIZE="SZ_8M"
CONFIG_BOOTM_LINUX=y
CONFIG_BOOTP_SEND_HOSTNAME=y
CONFIG_SYS_LDSCRIPT="board/ti/am335x/u-boot.lds"
CONFIG_SYS_SPL_ARGS_ADDR="(CONFIG_SYS_SDRAM_BASE + (128 << 20))"
CONFIG_ENV_OVERWRITE=y
CONFIG_ENV_SIZE="SZ_128K"
CONFIG_SYS_MALLOC_LEN="SZ_32M"
CONFIG_INITRD_TAG=y
CONFIG_SYS_BOOTM_LEN="SZ_16M"
CONFIG_SPL_FS_LOAD_ARGS_NAME="args"
CONFIG_SYS_OMAP24_I2C_SLAVE2=y
CONFIG_SYS_MMCSD_RAW_MODE_ARGS_SECTOR=0x1500
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_BOOTM_PLAN9=y
CONFIG_CLOCK_SYNTHESIZER=y
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_SPL_TEXT_BASE=$(CONFIG_ISW_ENTRY_ADDR)
CONFIG_SYS_MAXARGS=64
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_BOARDDIR="board/ti/am335x"
CONFIG_SYS_BOOTCOUNT_BE=y
CONFIG_TIMESTAMP=y
CONFIG_MAX_RAM_BANK_SIZE="(1024 << 20)"
CONFIG_NET_RETRY_COUNT=10
CONFIG_ZLIB=y
CONFIG_BOOTP_DNS2=y
CONFIG_SYS_NS16550_CLK=48000000
CONFIG_GZIP=y
CONFIG_SYS_MMCSD_RAW_MODE_ARGS_SECTORS=0x200
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_SYS_NS16550_COM1=0x44e09000
CONFIG_SYS_NS16550_COM2=0x48022000
CONFIG_SYS_NS16550_COM3=0x48024000
CONFIG_SYS_NS16550_COM4=0x481a6000
CONFIG_SYS_NS16550_COM5=0x481a8000
CONFIG_SYS_NS16550_COM6=0x481aa000
CONFIG_VAL(option)="config_val(option)"
CONFIG_SYS_SDRAM_BASE=0x80000000
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_USB_MUSB_DISABLE_BULK_COMBINE_SPLIT=y
CONFIG_PHY_ATHEROS=y
CONFIG_PHY_SMSC=y
CONFIG_AM335X_USB0=y
CONFIG_AM335X_USB1=y
CONFIG_SYS_SPL_MALLOC_START="(CONFIG_SPL_BSS_START_ADDR + CONFIG_SPL_BSS_MAX_SIZE)"
CONFIG_SYS_TIMERBASE=0x48040000
CONFIG_SPL_BSS_MAX_SIZE=0x80000
CONFIG_SPL_FS_LOAD_KERNEL_NAME="uImage"
CONFIG_SPL_BSS_START_ADDR=0x80a00000
CONFIG_SPL_PAD_TO=$(CONFIG_SPL_MAX_SIZE)
CONFIG_EXTRA_ENV_SETTINGS="DEFAULT_LINUX_BOOT_ENV DEFAULT_MMC_TI_ARGS DEFAULT_FIT_TI_ARGS "bootpart=0:20bootdir=/boot0bootfile=zImage0board_eeprom_header=undefined0fdtfile=undefined0console=ttyO0,115200n80partitions=uuid_disk=${uuid_gpt_disk};name=bootloader,start=384K,size=1792K,uuid=${uuid_gpt_bootloader};name=rootfs,start=2688K,size=-,uuid=${uuid_gpt_rootfs}0optargs=0ramroot=/dev/ram0 rw0ramrootfstype=ext20spiroot=/dev/mtdblock4 rw0spirootfstype=jffs20spisrcaddr=0xe00000spiimgsize=0x3620000spibusno=00spiargs=setenv bootargs console=${console} ${optargs} root=${spiroot} rootfstype=${spirootfstype}0ramargs=setenv bootargs console=${console} ${optargs} root=${ramroot} rootfstype=${ramrootfstype}0loadramdisk=load mmc ${mmcdev} ${rdaddr} ramdisk.gz0spiboot=echo Booting from spi ...; run spiargs; sf probe ${spibusno}:0; sf read ${loadaddr} ${spisrcaddr} ${spiimgsize}; bootz ${loadaddr}0pb_eeprom_hdr=mw 82001000 ee3355aa; mw 82001004 35333341; mw 82001008 4c4742500serverip=192.168.1.10ipaddr=192.168.1.20if_netconsole=ping $serverip0start_netconsole=setenv ncip $serverip; setenv bootdelay 10; setenv stdin serial,nc; setenv stdout serial,nc; setenv stderr serial,nc; version0preboot=run if_netconsole start_netconsole0eeprom_program=if test $board_eeprom_header = bbb_blank; then run eeprom_dump; run eeprom_blank; run eeprom_bbb_header; run eeprom_dump; reset; fi; if test $board_eeprom_header = bbbl_blank; then run eeprom_dump; run eeprom_blank; run eeprom_bbb_header; run eeprom_bbbl_footer; run eeprom_dump; reset; fi; if test $board_eeprom_header = bbbw_blank; then run eeprom_dump; run eeprom_blank; run eeprom_bbb_header; run eeprom_bbbw_footer; run eeprom_dump; reset; fi; if test $board_eeprom_header = pocketbeagle_blank; then run eeprom_dump; run eeprom_blank; run eeprom_pocketbeagle; run eeprom_dump; reset; fi; if test $board_eeprom_header = bbgg_blank; then run eeprom_dump; run eeprom_blank; run eeprom_bbb_header; run eeprom_bbgg_footer; run eeprom_dump; reset; fi; if test $board_eeprom_header = beaglelogic_blank; then run eeprom_dump; run eeprom_blank; run eeprom_beaglelogic; run eeprom_dump; reset; fi;  0ramboot=echo Booting from ramdisk ...; run ramargs; bootz ${loadaddr} ${rdaddr} ${fdtaddr}0findfdt=echo board_name=[$board_name] ...; if test $board_name = A335BLGC; then setenv fdtfile am335x-beaglelogic.dtb; fi; if test $board_name = A335BONE; then setenv fdtfile am335x-bone.dtb; fi; if test $board_name = A335BNLT; then echo board_rev=[$board_rev] ...; if test $board_rev = GH01; then setenv fdtfile am335x-boneblack.dtb; elif test $board_rev = BBG1; then setenv fdtfile am335x-bonegreen.dtb; elif test $board_rev = BP00; then setenv fdtfile am335x-pocketbone.dtb; elif test $board_rev = GW1A; then setenv fdtfile am335x-bonegreen-wireless.dtb; elif test $board_rev = GG1A; then setenv fdtfile am335x-bonegreen-gateway.dtb; elif test $board_rev = AIA0; then setenv fdtfile am335x-abbbi.dtb; elif test $board_rev = EIA0; then setenv fdtfile am335x-boneblack.dtb; elif test $board_rev = ME06; then setenv fdtfile am335x-bonegreen.dtb; elif test $board_rev = OS00; then setenv fdtfile am335x-osd3358-sm-red.dtb; else setenv fdtfile am335x-boneblack.dtb; fi; fi; if test $board_name = A335PBGL; then setenv fdtfile am335x-pocketbeagle.dtb; fi; if test $board_name = BBBW; then setenv fdtfile am335x-boneblack-wireless.dtb; fi; if test $board_name = BBG1; then setenv fdtfile am335x-bonegreen.dtb; fi; if test $board_name = BBGW; then setenv fdtfile am335x-bonegreen-wireless.dtb; fi; if test $board_name = BBGG; then setenv fdtfile am335x-bonegreen-gateway.dtb; fi; if test $board_name = BBBL; then setenv fdtfile am335x-boneblue.dtb; fi; if test $board_name = BBEN; then setenv fdtfile am335x-sancloud-bbe.dtb; fi; if test $board_name = OS00; then setenv fdtfile am335x-osd3358-sm-red.dtb; fi; if test $board_name = A33515BB; then setenv fdtfile am335x-evm.dtb; fi; if test $board_name = A335X_SK; then setenv fdtfile am335x-evmsk.dtb; fi; if test $board_name = A335_ICE; then setenv fdtfile am335x-icev2.dtb; fi; if test $fdtfile = undefined; then setenv board_name A335BNLT; setenv board_rev EMMC; setenv fdtfile am335x-bonegreen.dtb; fi; 0init_console=if test $board_name = A335_ICE; then setenv console ttyO3,115200n8;elif test $board_name = A335BLGC; then setenv console ttyO4,115200n8;else setenv console ttyO0,115200n8;fi;0" EEWIKI_NFS EEWIKI_BOOT EEWIKI_UNAME_BOOT EEPROM_PROGRAMMING NANDARGS NETARGS DFUARGS BOOTENV"
CONFIG_SYS_INIT_SP_ADDR="(NON_SECURE_SRAM_END - GENERATED_GBL_DATA_SIZE)"
CONFIG_SYS_I2C_EEPROM_ADDR_LEN=2
CONFIG_SYS_PTV=2
CONFIG_CMDLINE_TAG=y
CONFIG_ENV_EEPROM_IS_ON_I2C=y
CONFIG_ARCH_CPU_INIT=y
CONFIG_SYS_OMAP24_I2C_SPEED2=100000
CONFIG_SPL_MAX_SIZE="(SRAM_SCRATCH_SPACE_ADDR - CONFIG_SPL_TEXT_BASE)"
CONFIG_MACH_TYPE="MACH_TYPE_AM335XEVM"
CONFIG_POWER_TPS65910=y
CONFIG_AM335X_USB0_MODE="MUSB_PERIPHERAL"
CONFIG_SETUP_MEMORY_TAGS=y
CONFIG_CRC32=y
CONFIG_SYS_I2C_EEPROM_ADDR=0x50
CONFIG_LMB=y
CONFIG_SYS_MAX_FLASH_SECT=512
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_SYS_MMCSD_RAW_MODE_KERNEL_SECTOR=0x1700
CONFIG_AM335X_USB1_MODE="MUSB_HOST"
CONFIG_SPL_FS_LOAD_PAYLOAD_NAME="u-boot.img"
